### DISCUSSION TITLE
Treeless clones in GitHub Actions

### DISCUSSION THREAD

**Discussion by sliekens** [adamralph/minver#923] [General]
Hi,

The Git Checkout action for GitHub Actions recently got support for git clone `--filter`, which means you can now do a [partial clone](https://github.blog/2020-12-21-get-up-to-speed-with-partial-clone-and-shallow-clone/).

While typically not as fast as a shallow clone, a partial clone is still considerably faster than a full clone. More importantly, it allows fetching the entire commit history, which is needed for MinVer to work correctly.

To enable it:

``` yaml
steps:
  - name: Checkout
    uses: actions/checkout@v4
    with:
      fetch-depth: 0 # (no history limit)
      filter: tree:0
```

Update the action to v4 and add `filter: tree:0` to do a treeless clone. Note that you still need to override `fetch-depth: 0` to disable shallow cloning.

You can also do a blobless clone instead of a treeless clone with `filter: blone:none` if your workflow needs to get the history of a file (`git log -- <path>`). Otherwise git will start downloading the root trees for almost every commit in the history, which is painfully slow.

More info https://github.com/actions/checkout/pull/1396

Enjoy
