### ISSUE TITLE
Tags ignored with actions/checkout@v3

### ISSUE THREAD

**Issue by nspyke** [adamralph/minver#858]
## Version(s)

4.3.0

## To reproduce

```
jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Restore
        run: |
          dotnet tool restore
      - name: Version
        id: version
        run: |
          dotnet minver --verbosity trace
```

## Expected behaviour
Works the same as actions/checkout@v2

## Actual behaviour
```
MinVer: 112 commits checked.
MinVer: Ignoring { Commit: e1e1b31, Tag: '', Version: 0.0.0-alpha.0, Height: 86 }.
MinVer: No commit found with a valid SemVer 2.0 version. Using default version 0.0.0-alpha.0.
MinVer: Using    { Commit: 4dfec7e, Tag: '', Version: 0.0.0-alpha.0, Height: 85 }.
MinVer: The calculated version 0.0.0-alpha.0.85 satisfies the minimum major minor 0.0.
MinVer: Calculated version 0.0.0-alpha.0.85.
0.0.0-alpha.0.85
```

## Workarounds
Use deprecated `actions/checkout@v2`
Output from same repository using v2
```
MinVer: 3 commits checked.
MinVer: Using { Commit: 45440b9, Tag: '0.2.0', Version: 0.2.0, Height: 1 }.
MinVer: The calculated version 0.2.1-alpha.0.1 satisfies the minimum major minor 0.0.
MinVer: Calculated version 0.2.1-alpha.0.1.
0.2.1-alpha.0.1
```
